name: New Aqar Scraper Automation

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 05:00 KSA (02:00 UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ⚙️ Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip fonts-liberation libappindicator3-1 libatk-bridge2.0-0 \
            libatk1.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0 libnspr4 libnss3 libx11-xcb1 \
            libxcomposite1 libxdamage1 libxrandr2 xdg-utils jq xvfb libu2f-udev libasound2t64

      - name: ⚙️ Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium selenium-stealth undetected-chromedriver pandas openpyxl googletrans==4.0.0-rc1

      - name: 🧩 Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: 🧩 Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          echo "Installed Chrome version: $CHROME_VERSION"
          LATEST_CHROMEDRIVER=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | jq -r ".versions[] | select(.version | startswith(\"$CHROME_VERSION.\")) | .downloads.chromedriver[] | select(.platform == \"linux64\") | .url" | head -n 1)
          wget -O chromedriver.zip "$LATEST_CHROMEDRIVER"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: 🏃 Run the Aqar scraper script
        env:
          DISPLAY: ":99"
        run: |
          Xvfb :99 -ac &  # Virtual display for headless Chrome
          sleep 3
          python testing.py

      - name: 📦 Upload CSV output
        uses: actions/upload-artifact@v4
        with:
          name: aqar-scrape-results
          path: aqar_listings_final.csv
